                            List of relations
 Schema |                   Name                    |   Type   |  Owner  
--------+-------------------------------------------+----------+---------
 public | auth_group                                | table    | djkarma
 public | auth_group_id_seq                         | sequence | djkarma
 public | auth_group_permissions                    | table    | djkarma
 public | auth_group_permissions_id_seq             | sequence | djkarma
 public | auth_permission                           | table    | djkarma
 public | auth_permission_id_seq                    | sequence | djkarma
 public | auth_user                                 | table    | djkarma
 public | auth_user_groups                          | table    | djkarma
 public | auth_user_groups_id_seq                   | sequence | djkarma
 public | auth_user_id_seq                          | sequence | djkarma
 public | auth_user_user_permissions                | table    | djkarma
 public | auth_user_user_permissions_id_seq         | sequence | djkarma
 public | celery_taskmeta                           | table    | djkarma
 public | celery_taskmeta_id_seq                    | sequence | djkarma
 public | celery_tasksetmeta                        | table    | djkarma
 public | celery_tasksetmeta_id_seq                 | sequence | djkarma
 public | django_admin_log                          | table    | djkarma
 public | django_admin_log_id_seq                   | sequence | djkarma
 public | django_content_type                       | table    | djkarma
 public | django_content_type_id_seq                | sequence | djkarma
 public | django_session                            | table    | djkarma
 public | djcelery_crontabschedule                  | table    | djkarma
 public | djcelery_crontabschedule_id_seq           | sequence | djkarma
 public | djcelery_intervalschedule                 | table    | djkarma
 public | djcelery_intervalschedule_id_seq          | sequence | djkarma
 public | djcelery_periodictask                     | table    | djkarma
 public | djcelery_periodictask_id_seq              | sequence | djkarma
 public | djcelery_periodictasks                    | table    | djkarma
 public | djcelery_taskstate                        | table    | djkarma
 public | djcelery_taskstate_id_seq                 | sequence | djkarma
 public | djcelery_workerstate                      | table    | djkarma
 public | djcelery_workerstate_id_seq               | sequence | djkarma
 public | djkombu_message                           | table    | djkarma
 public | djkombu_message_id_seq                    | sequence | djkarma
 public | djkombu_queue                             | table    | djkarma
 public | djkombu_queue_id_seq                      | sequence | djkarma
 public | notes_course                              | table    | djkarma
 public | notes_course_id_seq                       | sequence | djkarma
 public | notes_file                                | table    | djkarma
 public | notes_file_id_seq                         | sequence | djkarma
 public | notes_file_tags                           | table    | djkarma
 public | notes_file_tags_id_seq                    | sequence | djkarma
 public | notes_file_votes                          | table    | djkarma
 public | notes_file_votes_id_seq                   | sequence | djkarma
 public | notes_instructor                          | table    | djkarma
 public | notes_instructor_id_seq                   | sequence | djkarma
 public | notes_level                               | table    | djkarma
 public | notes_level_id_seq                        | sequence | djkarma
 public | notes_reputationevent                     | table    | djkarma
 public | notes_reputationevent_id_seq              | sequence | djkarma
 public | notes_reputationeventtype                 | table    | djkarma
 public | notes_reputationeventtype_id_seq          | sequence | djkarma
 public | notes_school                              | table    | djkarma
 public | notes_school_id_seq                       | sequence | djkarma
 public | notes_sitestats                           | table    | djkarma
 public | notes_sitestats_id_seq                    | sequence | djkarma
 public | notes_tag                                 | table    | djkarma
 public | notes_tag_id_seq                          | sequence | djkarma
 public | notes_userprofile                         | table    | djkarma
 public | notes_userprofile_files                   | table    | djkarma
 public | notes_userprofile_files_id_seq            | sequence | djkarma
 public | notes_userprofile_id_seq                  | sequence | djkarma
 public | notes_userprofile_reputationEvents        | table    | djkarma
 public | notes_userprofile_reputationEvents_id_seq | sequence | djkarma
 public | notes_vote                                | table    | djkarma
 public | notes_vote_id_seq                         | sequence | djkarma
 public | social_auth_association                   | table    | djkarma
 public | social_auth_association_id_seq            | sequence | djkarma
 public | social_auth_nonce                         | table    | djkarma
 public | social_auth_nonce_id_seq                  | sequence | djkarma
 public | social_auth_usersocialauth                | table    | djkarma
 public | social_auth_usersocialauth_id_seq         | sequence | djkarma
 public | south_migrationhistory                    | table    | djkarma
 public | south_migrationhistory_id_seq             | sequence | djkarma
(74 rows)

